version: '3.7'

services:
  regression:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    command: /bin/sh -c "ls -la && pytest -sv --alluredir=allure-results"
    working_dir: /usr/workspace
    environment:
      - NAME = ${NAME}
      - PHONE_NUMBER = ${PHONE_NUMBER}
      - EMAIL = ${EMAIL}
      - COMPANY_NAME = ${COMPANY_NAME}
      - INFO_ABOUT_COMPANY = ${INFO_ABOUT_COMPANY}